language: java

sudo: required

services:
  - docker

before_install:
  - cd docker && bash ./dockbuild.sh

script:
  - bash ./testall || { [ -d target/surefire-reports ] && cat target/surefire-reports/*.dumpstream; false; }

